django_react_website/django_react_website/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include('frontend.urls')),
    re_path(r'^products/', include('products.urls')),
]

django_react_website/frontend/urls.py
from django.urls import path, re_path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name = 'Frontend'

urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name="index"),
]

django_react_website/products/urls.py
from django.urls import path, re_path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name = 'products'

urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name="index"),
    re_path(r'^(?P<pk>\d+)/$', views.ProductDetailView.as_view(), name='product-detail'),
    re_path(r'^api/(?P<pk>[0-9]+)/$', views.ProductAPIDetailView.as_view(), name='product-api-detail'),
    re_path(r'^api/products/$', views.ProductAPIListView.as_view(), name='product-api-detail'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

django_react_website/frontend/models.py
from django.db import models

# Create your models here.

django_react_website/products/models.py
from django.db import models

class Product(models.Model):
    sku = models.CharField(max_length=100)
    name = models.CharField(max_length=300)
    description = models.TextField()
    cost = models.FloatField()

    def __str__(self):
        return self.name

django_react_website/frontend/views.py
from django.views import generic
from products.models import Product


class IndexView(generic.list.ListView):
    template_name = 'frontend/index.html'
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_queryset(self):
        return Product.objects.order_by("sku")[:5]

django_react_website/products/views.py
from django.views import generic
from rest_framework import generics
from .serializers import ProductSerializer
from .models import Product


class IndexView(generic.list.ListView):
    template_name = 'products/index.html'
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_queryset(self):
        return Product.objects.order_by("sku")[:5]


class ProductDetailView(generic.detail.DetailView):
    template_name = "products/product.html"
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'] = Product.objects.get(id=self.kwargs['pk'])
        return context


class ProductAPIDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer


class ProductAPIListView(generics.ListCreateAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

django_react_website/frontend/templates/frontend/index.html
<!DOCTYPE html>
<html>

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'frontend/css/bootstrap.min.css' %}" type="text/css">
    <title>Django React - Playground</title>
</head>

<body>
    <div id="test"></div>
</body>

    <script src="{% static 'frontend/main.js' %}"></script>
</html>

django_react_website/products/templates/products/index.html
<h1>This is just the simple product list page</h1>

{% for item in object_list %}
    <h3><a href="{% url 'products:product-detail' item.id %}">{{ item.name }}</a> - {{ item.sku }}</h3>
    <p>{{ item.description|linebreaks }}</p><hr>
{% endfor %}

django_react_website/products/templates/products/product.html
<h1>{{ object.name }} - SKU:{{ object.sku }}</h1>

<p>{{ object.description|linebreaks }}</p><hr>